apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kibana
  namespace: logging
spec:
  hosts:
  - kibana.local.dev
  gateways:
  - istio-system/istio-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 5601
        host: elk-kibana
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: elk-client
  namespace: logging
spec:
  hosts:
  - es.local.dev
  gateways:
  - istio-system/istio-gateway-passthrough
  tls:
  - match:
    - sniHosts:
      - es.local.dev
    route:
    - destination:
        port:
          number: 9200
        host: elk-client