apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus
  namespace: monitoring
spec:
  hosts:
  - prometheus.local.dev
  gateways:
  - istio-system/istio-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 9090
        host: prometheus-operated
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  hosts:
  - alertmanager.local.dev
  gateways:
  - istio-system/istio-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 9093
        host: alertmanager-operated
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: karma
  namespace: monitoring
spec:
  hosts:
  - karma.local.dev
  gateways:
  - istio-system/istio-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8000
        host: karma
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  hosts:
  - blackbox-exporter.local.dev
  gateways:
  - istio-system/istio-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 9115
        host: blackbox-exporter-prometheus-blackbox-exporter
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: thanos
  namespace: monitoring
spec:
  hosts:
  - thanos.local.dev
  gateways:
  - istio-system/istio-gateway-passthrough
  tls:
  - match:
    - sniHosts:
      - thanos.local.dev
    route:
    - destination:
        port:
          number: 10901
        host: thanos-query     